AcademySoftwareFoundation/Imath

- README.md
> First complete draft of README.md for the Imath project

- README.md
> further edits of README.md

- .github/workflows/analysis_workflow.yml
Testing fixes for analysis testing. Before committing, they should be changed to only run on a schedule.
Signed-off-by: Owen Thompson <oxt3479@rit.edu>
> Changed analysis sonarcloud tests, run on pull request.

- CONTRIBUTING.md
- INSTALL.md
- README.md
> Clean up of repo docs.

- INSTALL.md
> Update INSTALL info on namespaces and cmake options

- docs/Doxyfile
- docs/conf.py
- docs/index.rst
> Fix copy/paste typos in Doxyfile and conf.py

- .github/workflows/analysis_workflow.yml
- .github/workflows/ci_workflow.yml
> CI: add VFX2021 jobs, enable coverage analysis

- docs/PortingGuide2-3.md
> First stab at Imath 2->3 porting guide

- Imath.pc.in
- src/python/PyImath.pc.in
- src/python/config/PyImathSetup.cmake
Also, fix Imath.pc.in and PyImath.pc.in
> PyImath installs headers into Imath subdirectory

- src/Imath/halfFunction.h
> Replace ILMBASE_HAVE_LARGE_STACK with IMATH_HAVE_LARGE_STACK

- src/ImathTest/testLimits.cpp
> Fix typo in comment in testHalfLimits

- README.md
- docs/PortingGuide2-3.md
- docs/index.rst
- docs/intro.rst
> Updates to README and docs.

- CHANGES.md
Signed-off-by: Cary Phillips cary@ilm.com
> 3.0.0 release notes

- src/Imath/ImathForward.h
- src/ImathTest/testBox.cpp
- src/ImathTest/testColor.cpp
- src/ImathTest/testFrustum.cpp
- src/ImathTest/testFrustumTest.cpp
- src/ImathTest/testInterval.cpp
- src/ImathTest/testLineAlgo.cpp
- src/ImathTest/testMatrix.cpp
- src/ImathTest/testQuat.cpp
- src/ImathTest/testRandom.cpp
- src/ImathTest/testShear.cpp
- src/ImathTest/testVec.cpp
> Forward declarations only if header is not included

- CHANGES.md
> Release notes for 3.0.1-beta

- CHANGES.md
> Release notes for 3.0.1

- .github/workflows/analysis_workflow.yml
* Steps more closely mirror ci_workflow.yml
* Remove unnecessary statements
* Remove fuzz test, since there aren't any.
> Clean up analysis_workflow.yml

- .github/workflows/analysis_workflow.yml
* restored build-wrapper call, needed by SonarCloud
* added "on workflow-dispatch" for manually triggering workflow
* temporarily added "on pull request"
Signed-off-by: Christina Tempelaar-Lietz <xlietz@gmail.com>
> Updated analysis workflow for SonarCloud

- CHANGES.md
> v3.1.0 release notes

- CHANGES.md
> Fix formatting in release notes

- src/Imath/CMakeLists.txt
Sort source files alphabetically
> Sort Imath source files

- CHANGES.md
> Release notes for v3.1.1

- CHANGES.md
> Release notes for v3.1.2

- CHANGES.md
> Release notes for v3.1.3

- CHANGES.md
Brought forward from the RB-3.1 branch.
> Release notes for 3.1.4

- CONTRIBUTING.md
- INSTALL.md
- README.md
- docs/PortingGuide2-3.md
- docs/conf.py
- docs/index.rst
> Change references to "master" branch to "main"

- .github/workflows/ci_workflow.yml
Signed-off-by: Christina Tempelaar-Lietz <xlietz@gmail.com>
> Update CI workflow matrix for VFX-CY2022.

- docs/requirements.txt
Update sphinx version from 4.0.3 to 4.4.0
> Update sphinx version

- src/Imath/ImathVec.h
Courtesy of @Jamaika1, see #264. 
> Add <cstdint> for int64_t

- CONTRIBUTING.md
- GOVERNANCE.md
Also, provide a local copy of GOVERNANCE.md
> Update CONTRIBUTING.md to be consistent with OpenEXR

- .github/workflows/analysis_workflow.yml
- .github/workflows/ci_workflow.yml
Added  minimal permissions statement as was done for OpenEXR CI: https://github.com/AcademySoftwareFoundation/openexr/pull/1417
> CI: Added minimal permissions.

- .github/workflows/ci_workflow.yml
See comments  here regarding 2023 updated CI for OpenEXR and Imath:
https://github.com/AcademySoftwareFoundation/openexr/pull/1475
> Updated CI with vfx2023 Linux jobs.

- website/requirements.txt
Apparently now required by other dependencies
> Require sphinx 5.0

- .github/workflows/release-notice.yml
Similar to OpenEXR (https://github.com/AcademySoftwareFoundation/openexr/pull/1601)
> GitHub action for release notices on Slack

- .github/workflows/analysis_workflow.yml
> Remove -Dsonar.login from sonar-scanner command line

- .github/workflows/analysis_workflow.yml
Updated docker image year and cxx standard from 14 to 17.
> Updated docker images to 2024.

- .github/workflows/ci_workflow.yml
Updated CI workflow to use 2024 docker images.
> Updated CI workflow to 2024 images.

- config/ImathConfig.h.in
- src/Imath/ImathRoots.h
ADM's Heterogeneous-computing Interface for Portability API, similar to CUDA.
See #462.
> Support HIP
