AcademySoftwareFoundation/Imath

- Imath/ImathBox.h
- Imath/ImathBoxAlgo.h
- Imath/ImathColor.h
- Imath/ImathColorAlgo.h
- Imath/ImathEuler.h
- Imath/ImathFrame.h
- Imath/ImathFrustum.h
- Imath/ImathFun.h
- Imath/ImathHalfLimits.h
- Imath/ImathInterval.h
- Imath/ImathLine.h
- Imath/ImathLineAlgo.h
- Imath/ImathMatrix.h
- Imath/ImathMatrixAlgo.cpp
- Imath/ImathPlane.h
- Imath/ImathQuat.h
- Imath/ImathRoots.h
- Imath/ImathShear.h
- Imath/ImathSphere.h
- Imath/ImathVec.h
- Imath/ImathVecAlgo.h
This is a first pass through Imath to add constexpr to functions that are contenders for compiler optimization.
> First pass at adding constexpr where useful

- Imath/ImathBox.h
- Imath/ImathBoxAlgo.h
- Imath/ImathColor.h
- Imath/ImathColorAlgo.h
- Imath/ImathEuler.h
- Imath/ImathFrustum.h
- Imath/ImathFun.h
- Imath/ImathLine.h
- Imath/ImathLineAlgo.h
- Imath/ImathMatrix.h
- Imath/ImathMatrixAlgo.cpp
- Imath/ImathPlane.h
- Imath/ImathQuat.h
- Imath/ImathRoots.h
- Imath/ImathShear.h
- Imath/ImathVec.h
- Imath/ImathVecAlgo.h
- config/ImathConfig.h.in
Changes were alluded to in a previous pull request. Getting this through early is beneficial as changes needed for CUDA integration will have a lot of conflicts with this PR if not done on top of them.
Previously, compilation with C++11 was not possible because of limited utility of constexpr. IMATH_CONSTEXPR14 is now used primarily on methods which are not return statements. It is defined under the condition that the compiler exceeds C++14, and is specified in config/ImathConfig.h.in
> Used macros to allow compilation with C++11 and constexpr

- Half/half.h
This implementation will simply place half into a namespace if compiling for the cuda kernel to prevent conflicts with the identically named cuda half type. 
Note: A few definitions needed to be moved around to avoid placing functions within the namespace and breaking existing testing. (operator <<, >>, and printBits)
Issues moving forward:
1: Testing of the cuda::half type's behaviour can be added, however the cuda half type is more picky about comparison and type conversion. For instance:
> half h1;
> ...
> assert (h1 == 1); 
Will produce compiler errors if written with the cuda half (but not for imath::half). It must instead be written this way:
> half h1;
> ...
> assert(float(h1) == 1);
2: The cuda half type also can not be created on __host__ code and therefore printing using cout …
> Simplest CUDA half type conflict resolution implementation.

- .git-blame-ignore-revs
Use this file with git-blame to ignore commits that have reformatted
old code according to the new clang-format style:
git blame --ignore-revs-file .git-blame-ignore-revs Imath/ImathVec.h
This helps preserve the old revision history, or at least makes it
more easily accessible.  Note that this requires git version 2.23 or
greater.
Also consider adding this to your git config:
git config blame.ignoreRevsFile .git-blame-ignore-revs
> Add .git-blame-ignore-revs to ignore reformatting

- Imath/ImathEuler.h
- Imath/ImathFrustum.h
- Imath/ImathMatrix.h
- Imath/ImathPlane.h
- Imath/ImathQuat.h
- Imath/ImathShear.h
- Imath/ImathSphere.h
- Imath/ImathVec.h
- Imath/ImathVecAlgo.h
Fixes #33 
Made various methods inline. Most notably all methods pertaining to vectors and matrices. 
Functions where omitted from the change if they were particularly long.
> Made various Imath/ header methods inline

- src/Imath/ImathInterval.h
- src/ImathTest/CMakeLists.txt
- src/ImathTest/main.cpp
- src/ImathTest/testInterval.cpp
- src/ImathTest/testInterval.h
The test for Imath::Interval was missing and it's not included
anywhere else in the library, so builds were not compiling it and thus
not catching syntax errors. These changes also bring it more in line
with the Box<T> class.
* misspelling of "constexpr"
* replace constexpr with IMATH_CONSTEXPR14
* add makeInfinite()/isInfinite() for similarity with Box<T>
* add operator<<
* add ImathTest/testInterval.cpp, based on testBox.cpp
> Fix problems with ImathInterval, and add test

- .github/workflows/analysis_workflow.yml
As per discussion in yesterday's meeting, part of the CI concerning sonarcloud has been disabled for PRs (only now running on push) so as to prevent it from failing redundantly because of issues with permissions.
> Stoped sonar cloud from running on PR

- src/ImathTest/CMakeLists.txt
- src/ImathTest/main.cpp
The list of tests is a bit duplicated, but adds to the clarity of what
is running and when
> Make separate test calls for each test

- CMakeLists.txt
- config/ImathSetup.cmake
If someone uses FetchContent then add_subdirectory, this correctly
disables the tests and clang format targets
> Fixes the subproject test

- src/ImathTest/testMatrix.cpp
> Fix two typos in m22 tests causing out of bounds references

- src/Imath/ImathMatrix.h
This is backporting some changes we made in OSL (with customized
versions of Imath headers that we can thankfully no longer need if we
push the fixes back to the Imath project). This was all pointed out by
people from Intel working on OSL, so I'm deferring to their judgment
that this is the best solution.
* Avoid memset or memcpy to initialize or copy a matrix, intead use
element-by-element copies. In a scalar context they generate the
same code (with the optimizer on, at least), but when those
operations are done inside a loop that you hope will be
auto-vectorized, the casting and function calling involved in using
memset/memcpy will confuse the vectorizer and you'll end up with
inferior code, sometimes even not vectorizing the whole loop.
* Replace a bunch of instances of accessing …
> Make Matrix implementation more SIMD friendly

- config/ImathConfig.h.in
- src/Imath/ImathColorAlgo.cpp
- src/Imath/ImathEuler.h
- src/Imath/ImathFrustum.h
- src/Imath/ImathLineAlgo.h
- src/Imath/ImathMath.h
- src/Imath/ImathMatrix.h
- src/Imath/ImathMatrixAlgo.h
- src/Imath/ImathQuat.h
- src/Imath/ImathRoots.h
- src/Imath/ImathSphere.h
- src/Imath/ImathVec.cpp
- src/Imath/ImathVec.h
- src/ImathTest/testColor.cpp
- src/ImathTest/testQuat.cpp
- src/ImathTest/testShear.cpp
- src/ImathTest/testVec.cpp
These were helpful to allow templated application of either double or
float in the olden days, but in C++11 and beyond, std:: versions of
these math functions do the same thing and should be preferred.
For back compatibility for applications, I'm keeping Math<T> but
defining them to just be the std:: versions. But the goal should be
to remove them eventually.
> Deprecate Math<T> in favor of std::

- config/ImathConfig.h.in
- src/Imath/ImathVec.h
Some compilers have special ways to indicate that a branch of an `if`
is especially likely or unlikely to be taken, and can do some
micro-optimizations based on that. Establish IMATH_LIKELY and
IMATH_UNLIKELY macros to implement this. (In C++20 and beyond, there
will be standard attributes for this, but it'll be a while before we
can rely on those.)
For a few conditions in the length and normalize methods of vectors,
in OSL we had replaced these functions with our own modified versions
after analysis from Intel engineers that these hints really did help
generate more performant code in these specific places. In this PR,
I'm pushing those improvements back to the Imath project itself.
These new macros should be used with caution -- programmers
notoriously guess wrong and can hurt …
> Use likely/unlikely to improve certain vector ops

- src/Imath/ImathVec.h
In Imath::Vec, remove IMATH_HOSTDEVICE from the few functions that
throw exceptions, since that's not supported in Cuda.
> Imath::Vec -- omit exception-throwing methods from Cuda side

- src/Imath/ImathVec.h
When I try to build the library with `g++-4.8` on `CentOS-7` I get following error: 
```
git/Imath/src/Imath/ImathVec.h: In member function ‘const Imath_3_0::Vec2<T>& Imath_3_0::Vec2<T>::normalizeExc()’:
git/Imath/src/Imath/ImathVec.h:1102:15: error: ‘domain_error’ is not a member of ‘std’
```
Adding necessary header file(`<stdexcept>`) to `ImathVec.h` solves the problem.
> Adding missing header

- src/Imath/ImathPlatform.h
This eliminates the very last place from the code base that said:
#if defined(__sgi)
Long live SGI.
> Simplify definition of IMATH_RESTRICT for modern supported compilers

- src/Imath/ImathBox.h
- src/Imath/ImathBoxAlgo.h
- src/Imath/ImathColor.h
- src/Imath/ImathColorAlgo.cpp
- src/Imath/ImathColorAlgo.h
- src/Imath/ImathEuler.h
- src/Imath/ImathFrame.h
- src/Imath/ImathFrustum.h
- src/Imath/ImathFrustumTest.h
- src/Imath/ImathFun.cpp
- src/Imath/ImathFun.h
- src/Imath/ImathHalfLimits.h
- src/Imath/ImathInterval.h
- src/Imath/ImathLimits.h
- src/Imath/ImathLine.h
- src/Imath/ImathLineAlgo.h
- src/Imath/ImathMath.h
- src/Imath/ImathMatrix.h
- src/Imath/ImathPlane.h
- src/Imath/ImathQuat.h
- src/Imath/ImathVec.h
- src/Imath/ImathVecAlgo.h
- src/Imath/half.cpp
- src/Imath/half.h
- src/Imath/halfLimits.h
This patch marks as noexcept absolutely everything that could be under
C++11 rules. Excluded are, obviously, anything that intentionally throws,
and those are very few after Owen's recent Imath overhaul and my changes
to eliminate the weird integer versions of normalize et al.
This patch also makes most of numeric_limits<half> constexpr, per
C++11 rules.  But a few are not constexpr yet because parts of half
still need to be fully constexpr-plumbed, and there are some tricky
parts (and maybe not 100% possible in C++11). I may revisit this in a
later patch.
Using `noexcept` is a promise that the caller to your function won't need
to handle exceptions. If your function calls something that turns out to
throw, it's on you to catch it, or else the application will crash with
an uncaught …
> noexcept all the things

- src/Imath/ImathHalfLimits.h
- src/ImathTest/testLimits.cpp
ImathHalfLimits.h was not included in any test or any other source file, so this typo hadn't gotten noticed.
> Incorrect constexpr in Imath::limits<half>, and missing test.

- src/Imath/half.h
This is the remaining section of `half` that can be easily constexpr.
The way they are currently implemented, the basic half-from-float ctr
and half-to-float cast are not able to be constexpr, and that in turn
prevents almost all the arithmetic operations (which convert to float,
do the math, then convert back) from being constexpr.
This is the closest we're going to get with the current implementations.
The most offensive parts to constexpr are the use of table lookups, and
the strange overflow() trying to raise a hardware overflow exception.
It's not hard to imagine alternate implementations that don't work the
same way at all, but we must leave that for another day (and maybe for
somebody who is more willing to chase down ever corner case of IEEE754
logic).
I added private mantissa() …
> constexpr as much of half as possible

- src/Imath/ImathQuat.h
- src/Imath/ImathSphere.h
* Restore Quat::BaseType typedef, which got lost inadvertently
* Initialize t in Sphere::intersect (must be initialized because the
function is now constexpr)
> Fix compiler errors from recent changes

- src/Imath/ImathGL.h
This file is not referenced by the unit tests so it got missed when removing references to Iex.
> Replace Iex::OverflowExc with std::invalid_argument

- src/python/PyImath/PyImathFixedArray.h
- src/python/PyImath/PyImathMathExc.h
- src/python/config/PyImathSetup.cmake
Remove the PY_IMATH_HANDLE_EXCEPTIONS option altogether.
With the removal of Iex from Imath and its wrapping of floating-point exceptions, there is no longer any need for the PY_IMATH_LEAVE/RETURN_PYTHON or MATH_EXC_ON macros.
> Drop support for exception-handling in PyImath

- src/Imath/ImathVec.h
> constexpr Vec2, Vec3, Vec4 constructors

- src/Imath/ImathFun.cpp
- src/Imath/ImathFun.h
- src/Imath/ImathInt64.h
- src/Imath/ImathRandom.cpp
- src/ImathTest/testMatrix.cpp
Leave the Int64/SInt64 types in place in ImathInt64.h with deprecation warnings, in case external code relies on them.
> Replace Int64/SInt64 with uint64_t/int64_t

- src/Imath/ImathBox.h
- src/Imath/ImathVec.h
- src/ImathTest/testBox.cpp
- src/python/PyImath/PyImathBox.cpp
- src/python/PyImath/PyImathBox.h
- src/python/PyImath/PyImathBox2Array.cpp
- src/python/PyImath/PyImathBox3Array.cpp
- src/python/PyImath/PyImathFixedArray.cpp
- src/python/PyImath/PyImathVec.h
- src/python/PyImath/PyImathVec2si.cpp
- src/python/PyImath/PyImathVec3si.cpp
- src/python/PyImath/PyImathVec3siArray.cpp
- src/python/PyImath/PyImathVec4si.cpp
- src/python/PyImath/PyImathVec4siArray.cpp
- src/python/PyImath/imathmodule.cpp
- src/python/PyImathTest/pyImathTest.in
Suggested by @ssteinbach for OpenTimelineIO
> Add int64_t specializations of Vec and Box.

- config/ImathConfig.h.in
- src/Imath/CMakeLists.txt
- src/Imath/ImathMatrix.h
- src/Imath/ImathPlatform.h
- src/Imath/ImathTypeTraits.h
- src/Imath/ImathVec.h
- src/ImathTest/CMakeLists.txt
- src/ImathTest/main.cpp
- src/ImathTest/testInterop.cpp
- src/ImathTest/testInterop.h
- src/ImathTest/testVec.cpp
This is a design review, feedback requested before I proceed further.
Trying out some use of enable_if to give `Vec3<T>` constructor and
assignment from unknown types that "look like" 3-vectors -- they have
a `operator[]` that returns a T, and their size is at least
3*sizeof(T).
The main idea is that if an app has rolled its own 3-vector class, it
can seamlessly construct a Vec3 from it, assign a Vec3 to it, or pass
their type as a parameter that expects a Vec3. And if the app's custom
3-vector class employs an equivalent idiom, all those operations will
work in the reverse direction.
It also works for std::vector, std::array, and even "initializer lists",
so all of this would work:
// Your app's special snowflake custom 3-vector type.
class YourCustomVec3 { ... };
// My library has an …
> Interoperability constructors

- config/CMakeLists.txt
- config/ImathConfig.h.in
- config/ImathSetup.cmake
- config/LibraryDefine.cmake
- src/Imath/ImathBox.h
- src/Imath/ImathBoxAlgo.h
- src/Imath/ImathColor.h
- src/Imath/ImathColorAlgo.h
- src/Imath/ImathEuler.h
- src/Imath/ImathExport.h
- src/Imath/ImathForward.h
- src/Imath/ImathFrustum.h
- src/Imath/ImathFrustumTest.h
- src/Imath/ImathInterval.h
- src/Imath/ImathMatrix.h
- src/Imath/ImathPlane.h
- src/Imath/ImathQuat.h
- src/Imath/ImathShear.h
- src/Imath/ImathSphere.h
- src/Imath/ImathVec.h
- src/Imath/half.h
This also exports public types for OS that need that for the typeinfo information.
NB: This does not change the python module yet, there is more work to do before that could work
> Make symbols hidden by default

- docs/PortingGuide2-3.md
When reading the porting guide I found a few typos.
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>
> fix several typos

- src/Imath/ImathTypeTraits.h
The Vec/Matrix interoperability constructors are already #if'd out for
older compilers. This #if's out the detector template definitions themselves,
which can cause errors with older compilers aside from the constructors.
> #if IMATH_FOREIGN_VECTOR_INTEROP around type detectors

- config/ImathConfig.h.in
Expose IMATH_LIB_VERSION as a cpp define, along with IMATH_VERSION, to aid in confirming what SOCURRENT.SOAGE.SOVERSION the library is built with.
> Lib version

- docs/PortingGuide2-3.md
> Add section on python bindings

- config/LibraryDefine.cmake
We were setting
target_compile_features(${objlib} PUBLIC cxx_std_${IMATH_CXX_STANDARD})
The PUBLIC forced downstream projects that consume the
ImathConfig*.cmake exports to use C++ standard at least as recent as
what Imath used to build (which defaults to 14).
But this is unnecessary. There's nothing in Imath's headers that
requires anything beyond C++11. So this patch uses a more fine-grained
setting of target properties to express this more correctly. Now it
will be fine for a C++11 project to consume Imath (via its exported
configs) even if that Imath happened to be built with C++14.
This change is exactly the same as
https://github.com/AcademySoftwareFoundation/openexr/pull/995
Signed-off-by: Larry Gritz lg@larrygritz.com
> Don't impose C++14 on downstream projects

- src/Imath/ImathFun.cpp
- src/ImathTest/testFun.cpp
And add more thorough test.
Should resolve https://github.com/AcademySoftwareFoundation/openexr/issues/999 for Imath v3.
Fix courtesy @christianaguilera-foundry.
> Fix regression in succf()/predf()

- CHANGES.md
- CMakeLists.txt
3.1.0 is the expected next release, so the best choice of version for the master branch? The version name will be "3.1.0-dev".
Also, update master branch release notes.
> Release notes for 3.0.2. Bump version on master branch to 3.1.0

- docs/Doxyfile
This gets the docs back functioning after recent changes (__cplusplus is necessary for the half changes). Preview of the updated docs is here:
https://cary-ilm-imath.readthedocs.io/en/latest/classes/half.html
The .rst setup doesn't currently pull in any of the overview doxygen coments (e.g. @file) from the headers such, that should be fleshed out.
> Add new macros to Doxyfile PREDEFINED

- src/Imath/ImathMatrix.h
`operator*` and `*=` muliplying two Matrix44s had two efficiency problems:
1. They both involved a temporary matrix using the default
constructor, which sets it to the identity matrix, before then
immediately putting other values into every element. (I think the
reason it did not use the special constructor that leaves it
uninitialized is because that conflicted with the desire for this
to be constexpr. Uninitialized data during its C++ visible lifetime
is a no-no for constexpr.)
2. It relied on the multiply() helper, which took the ADDRESS of
elements of the matrix. As discussed before in an earlier vector
ops overhaul, this interferes with good code generation when the
matrix multiply is inside a loop that we hope will
autovectorize. Taking the address of an array and then using that
as …
> Improve 4x4 matrix multiplication

- config/ImathConfig.h.in
- config/ImathSetup.cmake
- docs/Doxyfile
- src/Imath/ImathBox.h
- src/Imath/ImathBoxAlgo.h
- src/Imath/ImathColor.h
- src/Imath/ImathColorAlgo.cpp
- src/Imath/ImathColorAlgo.h
- src/Imath/ImathEuler.h
- src/Imath/ImathFrame.h
- src/Imath/ImathFrustum.h
- src/Imath/ImathFrustumTest.h
- src/Imath/ImathFun.cpp
- src/Imath/ImathFun.h
- src/Imath/ImathInterval.h
- src/Imath/ImathLine.h
- src/Imath/ImathLineAlgo.h
- src/Imath/ImathMath.h
- src/Imath/ImathMatrix.h
- src/Imath/ImathPlane.h
- src/Imath/ImathQuat.h
- src/Imath/ImathShear.h
- src/Imath/ImathVec.h
- src/Imath/ImathVecAlgo.h
- src/Imath/half.cpp
- src/Imath/half.h
- src/Imath/halfLimits.h
Legacy code that depends on the IlmBase v2 ExcMath mechanism of signal
handlers that throw exceptions is incompatible with noexcept, since
floating-point overflow and underflow can occur in computations within
Imath functions now marked with noexcept. Legacy code that needs to
accomodate the exception-handling behavior can disable the noexcept
specifier by defining the IMATH_NOEXCEPT macro to be empty. Otherwise,
IMATH_NOEXEPT defaults to "noexcept".
> IMATH_NOEXCEPT macro to make noexcept a compile-time option

- config/ImathConfig.h.in
- src/Imath/half.h
> silence a few warnings noticed with -Weverything

- src/ImathTest/CMakeLists.txt
Otherwise it doesn't get executed.
> Add testInterop to test list in define_imath_test()

- INSTALL.md
- README.md
* Describe new options, including IMATH_USE_HALF_LOOKUP_TABLES.
* Mention "release" branch
* Clean up description of other cmake options
> Update README.md and INSTALL.md for 3.1

- CMakeLists.txt
- config/LibraryDefine.cmake
- src/python/config/ModuleDefine.cmake
Reduce confusion between "VERSION", "REVISION", and "SOVERSION":
* Label the internal variable IMATH_LIBTOOL_* to indicate their purpose.
* Use terminology closer to the libtool description
* Add comment documenting the library update process
> Clean up library VERSION and SOVERSION

- INSTALL.md
- README.md
- config/CMakeLists.txt
- config/ImathConfig.h.in
- config/ImathSetup.cmake
- docs/classes/half.rst
- docs/half_conversion.rst
- docs/half_limits.rst
- docs/index.rst
- docs/install.rst
- docs/intro.rst
- src/Imath/half.cpp
- src/Imath/half.h
- src/ImathTest/CMakeLists.txt
- src/ImathTest/half_c_main.c
- src/ImathTest/half_perf_test.cpp
* Cmake option: IMATH_HALF_USE_LOOKUP_TABLE
* cpp #define:  IMATH_HALF_NO_LOOKUP_TABLE
* cpp #define:  IMATH_HALF_ENABLE_FP_EXCEPTIONS
I discarded the idea of reducing the two table options into a single setting, so this preserves the existing behavior but updates the names and explanations to hopefully be easier to follow.
Preview the readthedocs here: https://cary-ilm-imath.readthedocs.io/en/latest/
And the repo docs here: https://github.com/cary-ilm/Imath/tree/half-table-options
> Clean up half lookup-table options and related docs

- src/Imath/half.h
Is this the proper fix for #183? 
> Include <x86intrin.h> only if __x86_64__

- CMakeLists.txt
Per https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html:
* Source code has changed (PR #184), but no interface has been added, removed,
or changed: soversion goes from 29.0.0 to 29.1.0.
* Also, looks like IMATH_VERSION_RELEASE_TYPE was inadvertently left
at "-dev" for the v3.1.0 release.
> Bump version for v3.1.1 release on RB-3.1 branch

- src/Imath/half.h
* Don't use __has_include, it may report files exist when they don't.
* _WIN32 and __x86_64__ seem to be the most universal controls
> Improve handling of #include <*intrin.h>

- CHANGES.md
- CMakeLists.txt
- src/Imath/half.h
Make the handling of #include <*intrin.h> consistent with OpenEXR.
Because this is such a minor header change, I'm inclined to leave the soversion for 3.1.2 the same as 3.1.1, at 29.1.0, even though the strict interpretation of the rules should bump to 29.2.0.
> v3.1.2 fix, notes, and version bump (RB-3.1 branch)

- src/Imath/ImathMatrix.h
- src/Imath/ImathTypeTraits.h
Granted, the handling of namespaces is confusing and likely more flexible than necessary, since both the internal and external namespaces (i.e. "Imath_3_1::" and "Imath::") are configurable, but rather than open that can of worms, this fixes the current usages so it's at least consistent.
> Replace stray Imath:: with IMATH_INTERNAL_NAMESPACE::

- config/ImathConfig.h.in
> Guard `__has_attribute` for compilers that don't support it

- src/Imath/ImathBox.h
- src/Imath/ImathColor.h
- src/Imath/ImathEuler.h
- src/Imath/ImathFun.h
- src/Imath/ImathInterval.h
- src/Imath/ImathLine.h
- src/Imath/ImathMath.h
- src/Imath/ImathMatrix.h
- src/Imath/ImathPlane.h
- src/Imath/ImathQuat.h
- src/Imath/ImathRandom.h
- src/Imath/ImathShear.h
- src/Imath/ImathSphere.h
- src/Imath/ImathVec.h
Many places (basically everywhere), we had the following idiom:
template<class T>
class Foo {
IMATH_HOSTDEVICE float bar();    // declaration
};
...
template<class T> float Foo<T>::bar() { return 0.0; } // implementation
But this is wrong! When actually compiled in Cuda mode (maybe depending
on the compiler?), you can get errors about how you can't overload
a `__host__ __device__` declaration with a `__host__`-only implementation.
Which kinda makes sense. You have to match the two. So I have a WHOLE LOT
of places where I had to add IMATH_HOSTDEVICE.
Also, in ImathMath.h, we used this idiom:
IMATH_HOSTDEVICE IMATH_DEPRECATED("reason") float foo() { ... }
Now, this seems to work with `cudacc`, but when you use
`clang++ --language=cuda` to compile Cuda to PTX (it can do that!), clang
really …
> Cuda safety fixes

- src/python/PyImath/PyImathFixedVArray.cpp
This should address #195 and #197
> Fix undefined access of a vector when empty

- config/ImathSetup.cmake
- src/python/CMakeLists.txt
- src/python/PyImath/PyImathTask.cpp
Also removes thread library search, which is unused in this project.
the python support was exporting a custom library config (fine, although of dubious value, seems like that could just be simplified and merged to imath), but was not starting a new project definition, so was inheriting the same name, causing a duplicate export. It should be noted that this changes the requirements for making a release, where the version number needs to be updated in two places now to keep imath and pyimath in sync.
> Fix python imath export

- src/Imath/ImathFun.cpp
- src/ImathTest/testFun.cpp
isnan() and isinf() should more robust across different architectures than testing bit patterns.
Also, the unions should use uint32_t/uint64_t since they're guaranteed to be the appropriate size.
> Successor/predecessor functions use isnan() and isinf()

- src/python/CMakeLists.txt
- src/python/config/CMakeLists.txt
It is now just either on or off, not a separate project
> Remove extra project layer for the pyimath code

- src/python/PyImathTest/pyImathTest.in
`make test` fails on `testBinaryVecMethods` due to float error.
3.1.3
- OS: CentOS7
- Toolchain: GCC 11.2
- CPU: Broadwell
These `assert` with `==` fails on comparing `f[i].y` and `f1[i].cross(?)`.
https://github.com/AcademySoftwareFoundation/Imath/blob/6402a530a4b106181c058301a9580c866e6fe2f3/src/python/PyImathTest/pyImathTest.in#L589
https://github.com/AcademySoftwareFoundation/Imath/blob/6402a530a4b106181c058301a9580c866e6fe2f3/src/python/PyImathTest/pyImathTest.in#L604
Verified with `print`
print(f[i].y)
print(f1[i].cross(f2[i]).y)
7.900001525878906
7.900001049041748
This float errors only happen on these 2 asserts with `cross`. `make test` passes without failures with this PR.
> 100% tests passed, 0 tests failed out of 38
> Total Test time (real) =   5.63 sec
> Use equalWithAbsError instead of equal operator for float

- CMakeLists.txt
When Imath is a subproject (as with OpenEXR), the "docs" target can
conflict with the parent project's "docs" target. And the Imath docs
shouldn't be built by the parent project, anyway.
> Add docs target only if not a subproject

- src/Imath/ImathRoots.h
- src/ImathTest/testRoots.cpp
In some cases `solveNormalizedCubic` can return a real value from principled root that is a complex root. This happens in #86 for example. 
In case of discriminant `D > 0` there must be one real and two complex roots. Given formula: `-q/2 + sqrt(D)` might be a negative number.  Instead of searching though `y0`, `y1`, `y2` to find the real root, we can solve it as follows:
```
T sign = a < T (0) ? T (-1) : T (1);
return sign * std::pow (sign * a, T (1) / x);
```
> SolveNormalizedCubic fix to return proper real root

- src/Imath/half.h
This pull requests adds a missing check to fix building with VisualStudio on ARM64. The __lzcnt method is only supported on x86 or x64.
> Fix building of the project on ARM64 with VisualStudio 

- docs/half_limits.rst
- src/Imath/half.h
- src/Imath/halfLimits.h
- src/ImathTest/testLimits.cpp
Previously, these specializations have been in the header `halfLimit.h`,
but without this header, the` numeric_limits<>` template provides
default specializations that return 0, so, for example,
`std::numeric_limits<half>::min()` would silently return 0 in code that
inadvertently omitted the `#include <halfLimits.h>`.
The `numeric_limits` specializations should be considered an inseparable
part of the class definition.
This change moves the specializations directly into half.h and
deprecates the `halfLimits.h` header altogether. For backwards
compatibility, it includes `half.h` with a warning.
An alternative would be to keep `halfLimits.h` and include it in `half.h`,
but then each header would include the other circularly, which is
awkward.
Should address #240.
Signed-off-by: Cary …
> Move numeric_limits<half> specializations into half.h

- src/Imath/half.h
Add:
```
#if defined(__F16C__)
```
to the logic in half.h for including intrinsics header, which catches the i386 case.
Should address #239.
> Fix 32-bit x86 build failure with 16c instructions

- src/ImathTest/half_perf_test.cpp
Addresses #233. 
I looked at other usage of _MSC_VER and didn't see anything obviously amiss, but Windows/mingw users please confirm.
> Use _WIN32 instead of _MSC_VER to fix mingw build

- src/Imath/halfLimits.h
The issue with the warning of halfLimits.h being deprecated is that it
is very tempting to simply remove the include of halfLimits.h in favor
of simply half.h. However this change does depends on the version of
Imath used, and halfLimits.h should be kept for compatibility with
older version. Simply do not warn if short.h is already included.
> Do not warn if half.h has already being included

- README.md
> Fix markdown and typos in README.md

- src/Imath/ImathColor.h
- src/Imath/ImathEuler.h
- src/Imath/ImathQuat.h
- src/Imath/ImathShear.h
- src/Imath/half.h
* Hide x86 intrinsics from Cuda compilation (half.h) that is a hard
error when compiling for Cuda.
* Avoid warnings about host/device decorations for defaulted
destructors for Color3, Color4, Euler, Quat, and Shear classes -- if
you define the destructor as `= default`, you shouldn't also add the
IMATH_HOSTDEVICE decorator.
> Cuda safety in several headers

- src/Imath/ImathMatrixAlgo.h
- src/ImathTest/testExtractSHRT.cpp
If extractSHRT failes in computeRSMatrix, it's an error, so throw.
If extractSHRT fails in testMatrix in testExtractSHRT.cpp, it's fatal. The test was present for testMatrix(M33f) but missing for testMatrix(M44f). This lead to an uninitialized memory refererence since the failure leaves the arguments uninitialized.
> Test return value of extractSHRT to avoid uninitialized reference

- .github/workflows/ci_workflow.yml
- docs/examples/CMakeLists.txt
- docs/examples/Color3.cpp
- docs/examples/Color4.cpp
- docs/examples/Euler.cpp
- docs/examples/Frustum.cpp
- docs/examples/Interval.cpp
- docs/examples/Line3.cpp
- docs/examples/Matrix22.cpp
- docs/examples/Matrix33.cpp
- docs/examples/Matrix44.cpp
- docs/examples/Plane3.cpp
- docs/examples/Quat.cpp
- docs/examples/Sphere3.cpp
- docs/examples/Vec2.cpp
- docs/examples/Vec3.cpp
- docs/examples/Vec4.cpp
- docs/examples/intro.cpp
- docs/intro.rst
* Add missing includes
* Make intro example actually do something sensible, and move to intro.cpp
* Add building the example code to the CI
> Fix example code so it compiles as is 

- src/ImathTest/testRoots.cpp
> Initialize x in testRoots.cpp:solve() to suppress compiler warning

- src/python/PyImath/PyImathBufferProtocol.cpp
Courtesy of @cbreak-black, #266 
https://docs.python.org/3/c-api/buffer.html#c.PyBuffer_Release
https://docs.python.org/3/c-api/arg.html
> However, when a [Py_buffer](https://docs.python.org/3/c-api/buffer.html#c.Py_buffer) structure gets filled, the underlying buffer is locked so that the caller can subsequently use the buffer even inside a [Py_BEGIN_ALLOW_THREADS](https://docs.python.org/3/c-api/init.html#c.Py_BEGIN_ALLOW_THREADS) block without the risk of mutable data being resized or destroyed. As a result, you have to call [PyBuffer_Release()](https://docs.python.org/3/c-api/buffer.html#c.PyBuffer_Release) after you have finished processing the data (or in any early abort case).
> fix memory leak in V3fArrayFromBuffer

- src/ImathTest/testFun.cpp
PR #250 changed the %lx to %llx to suppress an MSVC warning, but it
introduced a gcc warning, where uint64_t is long, not long
long. Better to leave it as %lx and just cast to long. It's only a
printf anyway.
> Fix gcc compiler warning in testFun.cpp

- src/Imath/half.h
Meaningless, and generates a warning under MinGW
Should resolve #272 
> Remove export attribute from inline half::bits()/setBits()

- src/python/PyImath/PyImathBufferProtocol.cpp
- src/python/PyImath/PyImathFixedArray.h
- src/python/PyImath/PyImathFixedVArray.cpp
- src/python/PyImath/PyImathMatrix33.cpp
- src/python/PyImath/PyImathMatrix44.cpp
> Use Py_ssize_t in place of size_t where appropriate to avoid warnings

- config/ImathSetup.cmake
With cmake 3.0.0, CMP0042 applies and the default value of MACOSX_RPATH is true, this block is not needed  anymore.
Setting this is a bad practice because in some cases one needs to disabled it.
> Remove MACOSX_RPATH forcing

- src/Imath/ImathMatrixAlgo.h
Technically it's not necessary since extractSHRT will throw since the exc argument is implicitly true, but without testing the result, it generates a compiler warning.
> Check return status of extractSHRT in computeRSMatrix

- .github/workflows/analysis_workflow.yml
- share/ci/scripts/linux/run_gcov.sh
- src/ImathTest/CMakeLists.txt
Looks like the coverage analysis has been completely missing .c files.
- Set CMAKE_C_FLAGS/CMAKE_C_OUTPUT_EXTENSION_REPLACE just like CXX
- Fix run_gcov.sh to deduce the source file by examining the .o.d file rather than simply replacing .gcno with .cpp, which misses .c files
- Add ImathHalfPerfTest to the test suite
> Fix coverage analysis for .c files

- src/ImathTest/testMatrix.cpp
Avoid a double-to-float conversion warning
> In testMatrix(), call fabs() instead of fabsf() for double values

- src/ImathTest/CMakeLists.txt
- src/ImathTest/testBox.cpp
- src/ImathTest/testBoxAlgo.cpp
- src/ImathTest/testColor.cpp
- src/ImathTest/testMatrix.cpp
- src/python/PyImath/PyImathMatrix22.cpp
- src/python/PyImath/PyImathMatrix33.cpp
- src/python/PyImath/PyImathMatrix44.cpp
- src/python/PyImathTest/pyImathTest.in
- Add ImathHalfPerfTest as a test (it was built but not executed)
- Box<T>::isInfinite() tests
- Box<T>::affineTransform() tests with empty+infinite boxes
- rgb2hsv/hsv2rgb
- Add test code to python test for various matrix operators that were not covered
- Matrix22 tests were commented out for some unknown reason. 
- In Matrix22 and Matrix33, the python bindings now call setScale(s)
directly rather than calling setScale(Vec(s)). The behavior is the
same, but this ensures the scalar version of the method gets test coverage.
- In Matrix44:
* Call setScale(s) in place of setScale(Vec(s)), same as above.
* Similarly, call setShear(s) in place of setShear(Shear(s)). Same
behavior, better test.
* Add bindings for setEulerAngles() and setAxisAngles(), and
associated tests. The test suite relies …
> Extend test code coverage and add missing python bindings

- src/Imath/ImathMatrix.h
- src/ImathTest/CMakeLists.txt
- src/ImathTest/main.cpp
- src/ImathTest/testInterop.cpp
- src/ImathTest/testNoInterop.cpp
- src/ImathTest/testNoInterop.h
From the code coverage analysis, the ``Matrix44<>(const T a[4][4])``
constructors are overshadowed by the interoperability constructors
that match types with double-index operators, making them dead code. 
This change includes them only if the interoperability constructors are 
disabled at compile time.
It also adds a test to validate compilation with the interoperability
constructors disabled.
> Conditionally include Matrix constructors duplicated by interop declarations

- src/Imath/ImathMatrix.h
- src/ImathTest/testMatrix.cpp
PR #307 was incorrect, the array-based constructors are, in fact, necessary.  Although constructing a matrix from a 2D-array variable invokes the interop constructor:
```
const float a[2][2] = {{1,0},{0,1}};
M22f m(a);
```
constructing a matrix from a 2D array *parameter* uses the array constructor, which #307 thought was never used, because it was never invoked by the test suite:
```
void foo (const float a[2][2])
{
M22f m(a);
}
```
This restores the constructors and adds a test.
> Undo #307, restore array-based Matrix constructors

- src/Imath/ImathRandom.cpp
- src/ImathTest/testColor.cpp
- src/ImathTest/testFrustumTest.cpp
- src/ImathTest/testRandom.cpp
- src/python/PyImathTest/CMakeLists.txt
- src/python/PyImathTest/main.cpp
- src/python/PyImathTest/pyImathTest.in
- src/python/PyImathTest/testStringTable.cpp
- src/python/PyImathTest/testStringTable.h
- more colors for rgb2hsv/hsv2rgb
- misc Frustum methods
- FrustumTest::completelyContains
- drand48/lrand48
- 2D color array
- PyImathTestC tests wrap/convert (an internal ILM test that never got uploaded)
> Extend test coverage

- src/Imath/ImathMatrix.h
Somehow, a few methods got duplicate IMATH_HOSTDEVICE attributes, presumably a benign typo.
> Remove duplicate IMATH_HOSTDEVICE

- src/Imath/ImathRandom.h
Export just the one non-line method, not the entire class.
Hopefully, this addresses #311.
> IMATH_EXPORT for Rand32::nextf()

- .github/workflows/ci_workflow.yml
Updated MacOS jobs to use newer OS version per VFX ref platform 2023, kept one 2022 macos job.
Marked 2 Windows jobs as VFX ref platform 2023 and updated  them to use newer version of MSVC 2022 (17.5) available on the github 2022 runner image.
> Updated Mac and Windows jobs for VFX platform 2023.

- src/Imath/half.h
Hello,
I have been facing a problem conflicting two type alias `half` that are declared in Imath and [Thrust](https://github.com/NVIDIA/thrust) with CUDA.
`__CUDACC__` is defined when compiling CUDA source files, but Thrust with CUDA uses cuda_fp16.hpp in CUDA in host source files. So, two implementation of `half` conflict in host source files.
I added the condition determining whether using CUDA or not to the include guard of cuda_fp16.hpp. This prevents `half` from being re-defined by Imath when using Thrust with CUDA.
> fix the macro switching half floating-point format implementation.

- src/Imath/ImathMatrix.h
PR #198 added IMATH_HOSTDEVICE to the RB-3.1 branch, and PR #202 cherry-picked the change into main, but that cherry-pick somehow lost the IMATH_HOSTDEVICE on Matrix33<T>::invert(bool).
I discovered this some time ago but forgot to fix it at the time.
> Add missing IMATH_HOSTDEVICE to Matrix33<T>::invert(bool)

- SECURITY.md
openexr.com forwards to openexr.org, but for consistency, let's refer to all email addresses as @openexr.com, to match the website.
> Use security@openexr.com for consistency

- src/Imath/ImathFrustum.h
- src/Imath/ImathMatrix.h
- src/ImathTest/testFrustum.cpp
- src/ImathTest/testQuat.cpp
- src/ImathTest/testShear.cpp
- src/python/PyImath/PyImathEuler.cpp
- src/python/PyImath/PyImathFrustum.cpp
- src/python/PyImath/PyImathQuat.cpp
- src/python/PyImath/PyImathShear.cpp
- src/python/PyImath/imathmodule.cpp
- src/python/PyImathTest/pyImathTest.in
Working through the gcov/SonarCloud coverage report: https://sonarcloud.io/project/overview?id=AcademySoftwareFoundation_Imath
- Most functionality gets tested via the python test,  since that validates both the python and the C++ code. 
- Added a few new bindings to give python access (Quat "identity" and Euler "Layout" constructors in particular)
- Left comments where code appears to be unreachable, but it's hard to be 100% sure so I left the code in place.
> Improve test coverage for Frustum, Quat, Euler, Shear

- src/python/PyImathTest/pyImathTest.in
Extends epsilon bounds for extracted scale vector comparison to allow up to one representable value of deviation in precision. This matches behavior in the M33x tests.
> Expand epsilon bounds for m44x pyImath test

- src/python/PyImath/PyImathStringTable.cpp
- src/python/PyImath/PyImathUtil.h
Some of the code for the python bindings declares `__declspec(export)` on code without external linkage. MSVC behavior is to ignore these declarations, but they cause Clang on Windows to error out. This PR removes `PYIMATH_EXPORT` declarations on deleted functions in `PyImathUtil.h` and in an anonymous namespace in `PyImathStringTable.cpp`.
PyImathTest_Python3 and PyImathTestC tests fail in my environment, but that's unrelated to these changes.
> Fixed redundant PYIMATH_EXPORTS causing compile issues on Windows Clang

- src/Imath/ImathTypeTraits.h
As discussed in PR #334, I only fixed calling the default constructor of `C` in ImathTypeTraits.h by using uniform initialization. Could you please merge this PR?
> Fix calling default constructor by using uniform initialization.

- src/Imath/ImathFun.cpp
Hey. I didn't really deprecate them because there is no 1:1 equivalent in std. Instead I replaced the implementation to use std::nextafter. All tests pass.
> Changed implementation of succ and pred to use std::nextafter.

- src/ImathTest/testFun.cpp
See #346: Checking for the language version is not going to help for incomplete libraries such as on Apple or Android. This fixes this by using the bit_cast-specific macro.
> Fix check for the availability of std::bit_cast

- config/CMakeLists.txt
- config/ImathSetup.cmake
Similar to
https://github.com/AcademySoftwareFoundation/openexr/pull/1541, there seems to be no downside to generating the Imath.pc file even on windows, so for consistency, apply the same default to all platforms.
> IMATH_INSTALL_PKG_CONFIG is on by default, even on Windows

- src/Imath/half.h
The lzcnt instruction is not supported on some older x86_64 CPUs. On these CPUs it will silently execute a bsr instruction instead, leading to wrong results.
Instead use the bsr instruction and one additional subtraction, which should have a negligible impact on performance. Additionally, this likely improves performance on ARM.
Thanks to Ray Molenkamp for tracking down this bug.
> Fix half to float giving wrong results on older x86_64 CPUs on Windows

- .mailmap
- CONTRIBUTORS.md
The .mailmap file maps author/committer names and emails to canonical real names and email addresses.
This also updates the CONTRIBUTORS.md file with missing names from the git logs.
This information is to the best of our knowledge, but please submit any corrections if you prefer.
> Account for duplicate emails with .mailmap

- src/Imath/ImathMatrix.h
Hello,
I fixed a warning that `host` and `device` attributes are ignored by removing unnecessary `IMATH_HOSTDEVICE` attributes. Could you please merge this PR?
> Remove unnecessary IMATH_HOSTDEVICE attributes.

- config/CMakeLists.txt
Hello,
I encountered an error saying that `Imath` wasn't in any export set when adding Imath and Alembic by `add_subdirectory()`, so I made a change exporting Imath from a build tree and making each file path of `ImathConfig.cmake.in` and `ImathConfigVersion.cmake` exact.
However, this PR requires the following code
https://github.com/AcademySoftwareFoundation/Imath/blob/4d4e01c8c9fb9b9dbbefa2e135b21778c9cd331e/CMakeLists.txt#L58
and I can't understand the reason. So, if anyone have a better way, please feel free to tell me.
> Export Imath from a build tree.

- src/Imath/ImathFun.cpp
> Add std:: to isfinite in ImathFun.cpp

- src/Imath/ImathFun.cpp
A follow-up to https://github.com/AcademySoftwareFoundation/Imath/pull/368
Fixes: https://github.com/AcademySoftwareFoundation/Imath/issues/367
> ImathFun.cpp: add std:: to isfinite in remaining cases

- .github/workflows/release-sign.yml
- SECURITY.md
Replicates the openexr workflow:
https://github.com/AcademySoftwareFoundation/openexr/pull/1637
> Add workflow to sign release artifacts with Sigstore

- CMakeLists.txt
- website/install.rst
This should have gone into PR #366, since `file(CREATE_LINK)` was introduced in cmake 3.14, not sure how it slipped through the CI.
> Bump required cmake to 3.14

- website/install.rst
This should have gone into #339. It mirrors the description for OpenEXR.
> Update install instructions to reflect new SO versioning policy

- website/install.rst
_Hello everyone,_
I hope you'll find these changes useful.
_Best regards!_
> 🔗 Fix install URLs

- website/requirements.txt
Sphinx handling of `html_logo` and `html_favicon` changed in version 6, but changing to the documented `logo_url` and `favicon_url` still doesn't work for some reason. But Sphinx 5.3 works, so let's pin to that. This will need to get sorted out at some point, when there's a need to move to a newer sphinx.
> Pin RTD sphinx to 5.3

- website/_templates/layout.html
- website/conf.py
This adds the LF-recommended website copyright notice, with an ASWF logo:
Copyright © OpenEXR a Series of LF Projects, LLC.
For web site terms of use, trademark policy and other project policies please see https://lfprojects.org
Sphinx doesn't support fancy, multiline copyright footers, so the suggested alternative is raw html in the layout.html template.
And note that per LF policy, the copyright for website content is different from the copyright for source files.
> Add custom website footer with ASWF logo and proper copyright

- .github/workflows/website_preview_link.yml
Readthedocs triggers a build on PR, and a link is provided in the PR checks, but it's obscure. This action adds a link to the PR description, but only for PR's that actually modify the website.
> Add preview link to readthedocs build to PR description

- .github/workflows/ci_workflow.yml
Same as https://github.com/AcademySoftwareFoundation/openexr/pull/1779
They upgraded to a version that requires a glibc newer than is in the pre-2023 ASWF containers.
See AcademySoftwareFoundation/OpenImageIO#4324
The example build is failing, but it turns out the ci build step duplicates what happens in the validate_openexr_libs.sh script anyway, so I'm removing it from the workflow.
> Fix GHA CI after they upgraded nodejs

- src/Imath/half.h
Check for __HIP__ in addition to cuda (see #424)
> Fix redefinition of half when using with hip-runtime-amd

- src/pybind11/PyBindImath/CMakeLists.txt
- src/pybind11/PyBindImath/PyBindImath.h
- src/pybind11/PyBindImath/PyBindImathLine.cpp
- src/pybind11/PyBindImath/PyBindImathPlane.cpp
- src/pybind11/PyBindImath/pybindimathmodule.cpp
This is to fix issue #429.
I also added a rudimentary wrapper for Imath::Line, but this is only to allow for Imath::Plane's wrappings to work as a wrapping for Imath::Line didn't exist yet, though Imath::Plane's functions still utilized it. The Imath::Line wrapper currently only supports constructors and the << operator, though other functions could be added later.
> Add pybind11 wrappings for Imath::Plane

- src/Imath/ImathMatrix.h
- src/Imath/ImathShear.h
- src/Imath/ImathVec.h
If you take the address of a member, the pointer is only valid within the size of that member, such that accesses past that (i.e. to get to y or z of a vec3) are undefined behavior. by using this with a reinterpret cast, that tells the compiler the pointer space contains all values, and so avoids that. However, this may prevent other optimizations, so a larger change is recommended.
Addresses #446, thanks to @AlexMWells for the analysis
> Fix undefined behavior in operator[]

- src/Imath/ImathColor.h
Color4 does not derive from Vec4 the way Color3 derives from Vec3, so UB fix needed to avoid incorrect optimization in the presence of undefined behavior.
Should be included with patch release for #446
> Similar to previous Vec fixes, fix Color4 UB

- src/Imath/ImathBox.h
- src/Imath/ImathEuler.h
- src/Imath/ImathFrame.h
- src/Imath/ImathMatrixAlgo.cpp
- src/Imath/ImathMatrixAlgo.h
- src/Imath/ImathPlatform.h
- src/Imath/ImathVec.h
- src/python/PyImath/PyImathFixedArray.h
- src/python/PyImath/PyImathVec2Impl.h
- src/python/PyImathNumpy/imathnumpymodule.cpp
This is not actually changing much about the vec subscript operators at this point, other than once if consteval is available, accessing with literals / compile time constants will eliminate the dynamic array usage. However, this changes many places where Imath was using subscript operators to just access the vector elements directly, which may allow optimizers to just leave things in registers more
Part of addressing optimizations suggested in #446
> Add subscript operator optimizations, remove usage

- src/Imath/half.h
_mm_cvtps_ph doesn't support _MM_FROUND_NO_EXC. On Windows, if this is compiled, you will get the following warning:
`warning C4556: value of intrinsic immediate argument '8' is out of range '0 - 7'`
There is no corresponding instruction, so the flag should be removed.
References:
[https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_cvtps_ph&ig_expand=2244,2221,2220,2221,2252,2220,2221,2220,2221,2221,2107,2252,2107,2107](https://www.intel.com/content/www/us/en/docs/intrinsics-guide/index.html#text=_mm_cvtps_ph&ig_expand=2244,2221,2220,2221,2252,2220,2221,2220,2221,2221,2107,2252,2107,2107)
[https://developercommunity.visualstudio.com/t/-mm-cvtps-ph-doesnt-accept-mm-fround-no-exc/1343857](https://developercommunity.visualstudio.com/t/-mm-cvtps-ph-doesnt-accept- …
> Fix call to _mm_cvtps_ph in half.h

- src/pybind11/PyBindImath/CMakeLists.txt
- src/pybind11/PyBindImath/PyBindImath.h
- src/pybind11/PyBindImath/PyBindImathEuler.cpp
- src/pybind11/PyBindImath/PyBindImathFrustum.cpp
- src/pybind11/PyBindImath/pybindimathmodule.cpp
- The code had "Imath::" where it should have had "IMATH_NAMESPACE::
> S is not declared. Same thing in subsequent lines.
not working
> Fix Pybind11 Imath Frustum

- .github/workflows/ci_steps.yml
This requires all artifacts to have unique names, so the install_manifest.txt files need to uploaded with the name that includes the os and build number.
> Update actions/upload-artifact to @v4

- .github/workflows/ci_steps.yml
- src/pybind11/CMakeLists.txt
- src/pybind11/PyBindImath/CMakeLists.txt
- src/pybind11/PyBindImath/PyBindImath.h
- src/pybind11/PyBindImath/PyBindImathFun.cpp
- src/pybind11/PyBindImath/PyBindImathVec.cpp
- src/pybind11/PyBindImath/pybindimathmodule.cpp
- src/pybind11/PyBindImathTest/CMakeLists.txt
- src/pybind11/PyBindImathTest/pyBindImathTest
This does three things:
1. Completes the vector class wrapping, so all previous functionality is supported, including interoperability between vector classes (i.e. V2i + V2f), and interoperability between vectors and tuples and lists (i.e. V2i(1,2) + [1,2]).
2. Adds src/pybind11/PyBindImathTest/pyBindImathTest, which is a duplicate of the original test script for the Boost-based bindings, with the not-yet-implemented features commented out for now.
3. Adds wrappings for miscellaneous functions in PyImathFun.cpp, which are needed by the vector tests.
The vector class tests pass, so the pybind11 functionality is now consistent with existing Boost-based bindings.
All new wrappings should un-comment out the appropriate tests and validate that they pass.
> Complete pybind11 wrappings for V2, V3, V4, and add pyBindImathTest

- .github/workflows/ci_steps.yml
Collect args into a bash array and then join them into a single string with each entry quoted. This handles arguments with spaces much better.
> Fix quoting of cmake args in ci_steps.yml

- config/LibraryDefine.cmake
This flag is now specified via a generator expression, so it is only applied to C++ compilation, not CUDA.
This also makes the flag PRIVATE, not PUBLIC. It should not affect dependant projects, so it should not be a part of the public interface.
Resolves #476
> Fix handling of /EHsc flag

- src/pybind11/PyBindImath/CMakeLists.txt
- src/pybind11/PyBindImath/PyBindImath.h
- src/pybind11/PyBindImath/PyBindImathMatrix.cpp
- src/pybind11/PyBindImath/PyBindImathVec.cpp
- src/pybind11/PyBindImath/PyBindImathVec.h
- src/pybind11/PyBindImath/pybindimathmodule.cpp
- src/pybind11/PyBindImathTest/pyBindImathTest.py
This activates the tests for the Matrix22 and Matrix33 classes, float and double.
This does not include Matrix44, but that should slot in directly.
Note it does _not_ include the associated array classes, those are TBD.
> Add python bindings for M22f, M22d, M33f, M33d and associated tests

- .github/workflows/ci_workflow.yml
GitHub is deprecating windows-2019 runner, so drop coverage for VFX 2022.
> Update legacy Windows CI job from vfx2022 to vfx2023

- src/Imath/ImathEuler.h
- src/Imath/ImathFrustum.h
- src/Imath/ImathFrustumTest.h
- src/Imath/ImathLine.h
- src/Imath/ImathPlane.h
- src/pybind11/PyBindImath/CMakeLists.txt
- src/pybind11/PyBindImath/PyBindImath.h
- src/pybind11/PyBindImath/PyBindImathBox.cpp
- src/pybind11/PyBindImath/PyBindImathEuler.cpp
- src/pybind11/PyBindImath/PyBindImathFrustum.cpp
- src/pybind11/PyBindImath/PyBindImathLine.cpp
- src/pybind11/PyBindImath/PyBindImathMatrix.cpp
- src/pybind11/PyBindImath/PyBindImathPlane.cpp
- src/pybind11/PyBindImath/PyBindImathQuat.cpp
- src/pybind11/PyBindImath/PyBindImathRandom.cpp
- src/pybind11/PyBindImath/PyBindImathShear.cpp
- src/pybind11/PyBindImath/PyBindImathVec.h
- src/pybind11/PyBindImath/PyBindImathVec2.cpp
- src/pybind11/PyBindImath/PyBindImathVec3.cpp
- src/pybind11/PyBindImath/PyBindImathVec4.cpp
- src/pybind11/PyBindImath/pybindimathmodule.cpp
- src/pybind11/PyBindImathTest/pyBindImathTest.py
This completes the wrappings for the non-array Imath classes. The non-array tests in pyBindImathTest.py pass (mostly).
Reminder that the strategy in introducing pybind11 wrappings is to get the current test for the boost-based bindings, src/python/PyImathTest/pyImathTest.py, to execute successfully with the pybind11 bindings. The test has been copied to src/pybind11/PyBindImathTest/pyBindImathTest.py, with the not-yet-succeeding tests commented out, then as the bindings are completed, un-commenting them out to verify the behavior.
A few issues remain:
- Doc strings still need to be ported
- Return values from operators are not all correct, even though the tests pass.
- A few floating-point conversion issues remain as TODO's in the tests
> pybind11 wrappings for Color, Euler, Frustum, Line, Plane, Quat, Shear, Random
